### ISSUE TITLE
mdsf applies changes outside code snippet

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#138] opened 2024-04-01 09:54 UTC
I love your tool idea.

I can see you are actively working on it, so first of all, thank you !

Here are the kind of replacement I noticed

````mardown
# title

Let's play!

Have some fun...

I like "mdsf"

| Field            | Description            |
|------------------|------------------------|
| foo              |   foo field            |
| bar              |   bar field            |

```shell
ls
```
````

will become 

````mardown
# title

Let’s play!

Have some fun…

I like “mdsf”

|Field|Description|
|-----|-----------|
|foo|foo field|
|bar|bar field|

```shell
ls
```
````

The table formatting is broken. It will render OK in markdown, but the text was altered.

You might not notice at first but it replaces:
- ... (three consecutive dots) into    U+2026 	…	HORIZONTAL ELLIPSIS
- simple quote by U+2019 ’ RIGHT SINGLE QUOTATION MARK
- double quoted text by text surrounded by:
  - U+201D 	”	RIGHT DOUBLE QUOTATION MARK
  - U+201C 	“	LEFT DOUBLE QUOTATION MARK

I would expect the code to only apply changes on the block quotes

**Comment by ccoVeille** [comment] 2024-04-01 10:10
I can confirm it only apply changes when the markdown code contains at least one code snippet

This won't be altered

````mardown
# title

Let's play!

I like "mdsf"

| Field            | Description            |
|------------------|------------------------|
| foo              |   foo field            |
| bar              |   bar field            |

````

**Comment by hougesen** [comment] 2024-04-01 18:25
Hello @ccoVeille, glad to hear you like the idea! 😄

I just pushed a fix for the quote and ellipsis issue.

The table formatting is a bit trickier, since it is caused by the markdown parser used ([pulldown-cmark](https://github.com/pulldown-cmark/pulldown-cmark)), not taking into account unnecessary spaces and `-` in tables.

For now your best option would be to enable a markdown formatter in your `mdsf.json`.

```json
{
  "markdown": {
    "enabled": true,
    "formatter": ["prettier"]
  }
}
```

**Comment by ccoVeille** [comment] 2024-04-01 18:53
You are parsing the markdown files via a lib to identity each code snippet in the markdown.

But then, I assume you are replacing the markdown content in the parsed content, and generate the whole document.

Would it be possible to "simply" (™️) replace the snippet zone as text in the markdown content you opened.

Thanks for the setting, I'll try. Side note, I would have expected this setting to only apply on code snippet is markdown

So something like that

`````markdown
Here are how to make a document title in markdown
````markdown
# Title
````
`````

All these put together, it could lead to have a way to format the markdown of the documents (so not the snippet) only if requested (but it could be activated by default)

**Comment by ccoVeille** [comment] 2024-04-01 19:33
Please note that current code also rewrite markdown such as

```markdown
1. Foo
2. Bar
```

To

```markdown
1. Foo
1. Bar
```

Or list from

```markdown
* Foo
* Bar
```

To

```markdown
- Foo
- Bar
```

And emphasis from

```markdown
Foo *bar*
```

To 

```markdown
Foo _bar_
```

**Closed** 2024-04-01 20:26 UTC

**Comment by ccoVeille** [comment] 2024-04-01 20:31
I confirm the latest code fix the issue I raised, thanks a lot for taking into account

**Comment by hougesen** [comment] 2024-04-01 20:38
Awesome! 😄 

> Thanks for the setting, I'll try. Side note, I would have expected this setting to only apply on code snippet is markdown

That is a very good point, I'll split it out to reduce any confusion 👍🏼

**Comment by ccoVeille** [comment] 2024-04-01 21:13
> Awesome! 😄
> 
> > Thanks for the setting, I'll try. Side note, I would have expected this setting to only apply on code snippet is markdown
> 
> That is a very good point, I'll split it out to reduce any confusion 👍🏼

For records, it was applied here https://github.com/hougesen/mdsf/pull/143
